### ISSUE TITLE
Ran this stript and node-RED UI doesn't load

### ISSUE THREAD

**Issue by donavanbecker** [hoobs-org/hoobs-node-red#3]

**Comment by markus-fischbacher** [comment]
The symlink to node-red-pi is not set.
/usr/local/bin/node-red-pi is missing. Create it manually and it works.

**Comment by d0n4v4nb3ck3r** [comment]
how do you create it manually. is there a command to create it?

**Comment by markus-fischbacher** [comment]
My installation could be fixed with that command:
```
cd /usr/local/bin
sudo ln -s /home/hoobs/.node-red/node_modules/.bin/node-red-pi node-red-pi
```

**Comment by d0n4v4nb3ck3r** [comment]
did all that and still didn't load up

**Comment by markus-fischbacher** [comment]
Any hints or errors in logs found?

**Comment by d0n4v4nb3ck3r** [comment]
What log? Nothing even pops up and it’s not in HOOBs HomeBridge log

**Comment by markus-fischbacher** [comment]
Quite after boot attempt, open terminal and execute
`sudo journalctl -xe`
and have a look for errors.

**Comment by Fookes74** [comment]
I have this exact issue. I too have input the suggested commands that Markus suggests, but these have made no difference. I am unable to access the NodeRED UI. I have also run sudo journalctl -xe and this is the only output. Any help to get this working would be appreciated. 
![Screenshot 2020-02-26 at 13 56 30](https://user-images.githubusercontent.com/37369430/75351407-0a5b7900-58a0-11ea-8589-4aa21de797cc.png)

**Comment by Fookes74** [comment]
This may assist. When I ran the NodeRED install script in terminal I did notice this line on completion:

bash: line 13: cd: /home/hoobs/.node-red: No such file or directory

**Comment by markus-fischbacher** [comment]
Search for the node-red-pi program.
`sudo find / -name node-red-pi`

**Comment by Fookes74** [comment]
Done that and this is the output:

hoobs@**********:~/.hoobs/etc $ sudo find / -name node-red-pi
/usr/local/bin/node-red-pi
/home/hoobs/.hoobs/node_modules/node-red/bin/node-red-pi
/home/hoobs/.hoobs/node_modules/.bin/node-red-pi
hoobs@***********:~/.hoobs/etc $

**Comment by markus-fischbacher** [comment]
Ok, you have a different issue than I had. Your binary seems to be fine.
/usr/local/bin/node-red-pi
Unfortunately I don‘t have a running system right now. Can only make suggestions out of my brain.

**Comment by Fookes74** [comment]
Appreciate you looking at this. I'm happy to try out any suggestions you have. Someone at HOOBS said that they'd be looking at this for me today but I'm happy to try and remedy before that.

**Comment by markus-fischbacher** [comment]
Try to run the following command:
`node-red-pi --max-old-space-size=256`

**Comment by Fookes74** [comment]
I get this:
~/.hoobs/etc $ node-red-pi --max-old-space-size=256
bash: node-red-pi: command not found

**Comment by markus-fischbacher** [comment]
Ok, the path /usr/local/bin is not in your environments PATH variable. 
Add the follwing line to ~/.profile
`export PATH=$PATH:/usr/local/bin`
and after saving execute
`sudo source ~/.profile`
and try again.

**Comment by Fookes74** [comment]
I'm sorry. I'm not particularly proficient in this sort of thing. How do I get to ~/.profile?

**Comment by Fookes74** [comment]
I have this at present:

![Screenshot 2020-02-27 at 13 27 41](https://user-images.githubusercontent.com/37369430/75449502-fcbbf700-5964-11ea-8267-f87a487b2f22.png)

**Comment by markus-fischbacher** [comment]
Run that command
`echo 'export PATH=/usr/local/bin:$PATH' >> ~/.profile`

Then run
`sudo source ~/.profile`

**Comment by BobbySlope** [comment]
script is fixed now

**Comment by kbardai** [comment]
Hey, will this script only work on hoobs installed on a raspberry-pi or can I also run this script with hoobs running on a x86_64 ubuntu box to get node-red running?

**Comment by johnschult** [comment]
@kbardai It looks like pi only.
